[package]
name = "contract"
version = "0.1.0"
edition = "2024"

[dependencies]
borsh = "1.5.7"
pinocchio = "0.9"
serde = "1.0.219"
serde_json = "1.0.143"
solana-program = "1.18.14"
spl-token = "8.0.0"
